[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "plctestbench"
version = "0.10.0"
description = "Framework comparison and benchmarking of error concealment algorithms"
readme = "README.md"
authors = [
    { name = "Luca Vignati", email = "luca.vignati@vignati.net" },
    { name = "Filippo Daniotti", email = "fpp.daniotti@gmail.com" },
]
maintainers = [{ name = "Filippo Daniotti", email = "fpp.daniotti@gmail.com" }]
license = { text = "Your license here" }
classifiers = ["Programming Language :: Python :: 3"]

[tool.poetry.dependencies]
essentia = "2.1b6.dev1389"
python = "3.11,<3.12"
numpy = { version = "1.26.0", python = ">=3.10,<3.13" }
soundfile = "0.12.1"
anytree = { version = "2.12.1", python = ">=3.10,<4.0" }
pymongo = "4.10.1"
tqdm = "4.67.1"
matplotlib = "3.9.3"
typing_inspect = "*"
tinydb = { version = "4.8.2", python = ">=3.10,<4.0" }
ruamel-yaml = "0.18.6"
ruamel-yaml-clib = "0.2.12"
librosa = "0.10.1"
scipy = "1.14.1"
pandas = "^2.2.3"
# burg-plc = { git = "https://github.com/CIMIL/burg-python-bindings.git", markers = "platform_system == 'Linux'" }
# tensorflow = { version = "2.15", markers = "platform_system == 'Linux'" }

[tool.poetry.group.notebook]
optional = true

[tool.poetry.group.notebook.dependencies]
ipywidgets = "^8.1.5"
ipykernel = "6.30.1"

# [tool.poetry.group.cpp_template]
# optional = true

# [tool.poetry.group.cpp_template.dependencies]
# cpp-plc-template = { git = "https://github.com/LucaVignati/cpp_plc_template.git" }
